require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe BarcodesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Barcode. As you add validations to Barcode, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { FactoryGirl.attributes_for(:barcode) }
  let(:invalid_attributes) { FactoryGirl.attributes_for(:invalid_barcode) }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BarcodesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all barcodes as @barcodes" do
      barcode = Barcode.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:barcodes)).to eq([barcode])
    end
  end

  describe "GET #show" do
    it "assigns the requested barcode as @barcode" do
      barcode = Barcode.create! valid_attributes
      get :show, {:id => barcode.to_param}, valid_session
      expect(assigns(:barcode)).to eq(barcode)
    end
  end

  describe "GET #new" do
    it "assigns a new barcode as @barcode" do
      get :new, {}, valid_session
      expect(assigns(:barcode)).to be_a_new(Barcode)
    end
  end

  describe "GET #edit" do
    it "assigns the requested barcode as @barcode" do
      barcode = Barcode.create! valid_attributes
      get :edit, {:id => barcode.to_param}, valid_session
      expect(assigns(:barcode)).to eq(barcode)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Barcode" do
        expect {
          post :create, {:barcode => valid_attributes}, valid_session
        }.to change(Barcode, :count).by(1)
      end

      it "assigns a newly created barcode as @barcode" do
        post :create, {:barcode => valid_attributes}, valid_session
        expect(assigns(:barcode)).to be_a(Barcode)
        expect(assigns(:barcode)).to be_persisted
      end

      it "redirects to the created barcode" do
        post :create, {:barcode => valid_attributes}, valid_session
        expect(response).to redirect_to(Barcode.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved barcode as @barcode" do
        post :create, {:barcode => invalid_attributes}, valid_session
        expect(assigns(:barcode)).to be_a_new(Barcode)
      end

      it "re-renders the 'new' template" do
        post :create, {:barcode => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) { FactoryGirl.attributes_for(:updated_valid_barcode) }

      it "updates the requested barcode" do
        barcode = Barcode.create! valid_attributes
        put :update, {:id => barcode.to_param, :barcode => new_attributes}, valid_session
        barcode.reload
      end

      it "assigns the requested barcode as @barcode" do
        barcode = Barcode.create! valid_attributes
        put :update, {:id => barcode.to_param, :barcode => valid_attributes}, valid_session
        expect(assigns(:barcode)).to eq(barcode)
      end

      it "redirects to the barcode" do
        barcode = Barcode.create! valid_attributes
        put :update, {:id => barcode.to_param, :barcode => valid_attributes}, valid_session
        expect(response).to redirect_to(barcode)
      end
    end

    context "with invalid params" do
      it "assigns the barcode as @barcode" do
        barcode = Barcode.create! valid_attributes
        put :update, {:id => barcode.to_param, :barcode => invalid_attributes}, valid_session
        expect(assigns(:barcode)).to eq(barcode)
      end

      it "re-renders the 'edit' template" do
        barcode = Barcode.create! valid_attributes
        put :update, {:id => barcode.to_param, :barcode => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested barcode" do
      barcode = Barcode.create! valid_attributes
      expect {
        delete :destroy, {:id => barcode.to_param}, valid_session
      }.to change(Barcode, :count).by(-1)
    end

    it "redirects to the barcodes list" do
      barcode = Barcode.create! valid_attributes
      delete :destroy, {:id => barcode.to_param}, valid_session
      expect(response).to redirect_to(barcodes_url)
    end
  end

end
