require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe RfidReadersController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # RfidReader. As you add validations to RfidReader, be sure to
  # adjust the attributes here as well.
  before(:each) do
    address = FactoryGirl.create(:address)
    @hospital = FactoryGirl.create(:hospital, address_id: address.id)
    rfid_reader = FactoryGirl.build(:rfid_reader, hospital_id: @hospital.id)
  end

  let(:valid_attributes) { FactoryGirl.attributes_for(:rfid_reader, hospital_id: @hospital.id)}
  let(:invalid_attributes) { FactoryGirl.attributes_for(:invalid_rfid_reader, hospital_id: nil) }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RfidReadersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all rfid_readers as @rfid_readers" do
      rfid_reader = RfidReader.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:rfid_readers)).to eq([rfid_reader])
    end
  end

  describe "GET #show" do
    it "assigns the requested rfid_reader as @rfid_reader" do
      rfid_reader = RfidReader.create! valid_attributes
      get :show, {:id => rfid_reader.to_param}, valid_session
      expect(assigns(:rfid_reader)).to eq(rfid_reader)
    end
  end

  describe "GET #new" do
    it "assigns a new rfid_reader as @rfid_reader" do
      get :new, {}, valid_session
      expect(assigns(:rfid_reader)).to be_a_new(RfidReader)
    end
  end

  describe "GET #edit" do
    it "assigns the requested rfid_reader as @rfid_reader" do
      rfid_reader = RfidReader.create! valid_attributes
      get :edit, {:id => rfid_reader.to_param}, valid_session
      expect(assigns(:rfid_reader)).to eq(rfid_reader)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new RfidReader" do
        expect {
          post :create, {:rfid_reader => valid_attributes}, valid_session
        }.to change(RfidReader, :count).by(1)
      end

      it "assigns a newly created rfid_reader as @rfid_reader" do
        post :create, {:rfid_reader => valid_attributes}, valid_session
        expect(assigns(:rfid_reader)).to be_a(RfidReader)
        expect(assigns(:rfid_reader)).to be_persisted
      end

      it "redirects to the created rfid_reader" do
        post :create, {:rfid_reader => valid_attributes}, valid_session
        expect(response).to redirect_to(RfidReader.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved rfid_reader as @rfid_reader" do
        post :create, {:rfid_reader => invalid_attributes}, valid_session
        expect(assigns(:rfid_reader)).to be_a_new(RfidReader)
      end

      it "re-renders the 'new' template" do
        post :create, {:rfid_reader => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) { FactoryGirl.attributes_for(:updated_valid_rfid_reader, hospital_id: @hospital.id) }


      it "updates the requested rfid_reader" do
        rfid_reader = RfidReader.create! valid_attributes
        put :update, {:id => rfid_reader.to_param, :rfid_reader => new_attributes}, valid_session
        rfid_reader.reload
      end

      it "assigns the requested rfid_reader as @rfid_reader" do
        rfid_reader = RfidReader.create! valid_attributes
        put :update, {:id => rfid_reader.to_param, :rfid_reader => valid_attributes}, valid_session
        expect(assigns(:rfid_reader)).to eq(rfid_reader)
      end

      it "redirects to the rfid_reader" do
        rfid_reader = RfidReader.create! valid_attributes
        put :update, {:id => rfid_reader.to_param, :rfid_reader => valid_attributes}, valid_session
        expect(response).to redirect_to(rfid_reader)
      end
    end

    context "with invalid params" do
      it "assigns the rfid_reader as @rfid_reader" do
        rfid_reader = RfidReader.create! valid_attributes
        put :update, {:id => rfid_reader.to_param, :rfid_reader => invalid_attributes}, valid_session
        expect(assigns(:rfid_reader)).to eq(rfid_reader)
      end

      it "re-renders the 'edit' template" do
        rfid_reader = RfidReader.create! valid_attributes
        put :update, {:id => rfid_reader.to_param, :rfid_reader => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested rfid_reader" do
      rfid_reader = RfidReader.create! valid_attributes
      expect {
        delete :destroy, {:id => rfid_reader.to_param}, valid_session
      }.to change(RfidReader, :count).by(-1)
    end

    it "redirects to the rfid_readers list" do
      rfid_reader = RfidReader.create! valid_attributes
      delete :destroy, {:id => rfid_reader.to_param}, valid_session
      expect(response).to redirect_to(rfid_readers_url)
    end
  end

end
